### ISSUE TITLE
No handlers could be found for logger

### ISSUE THREAD

**Issue by kjde** [mathiasertl/django-xmpp-account#11]
The following message appears when I run 'python manage.py compilemessages' after an update:

No handlers could be found for logger "xmppaccount.settings"
CommandError: This script should be run from the Django Git checkout or your project or app tree, or with the settings module specified.

I'm in ./django-xmpp-account which is my git dir.

The Website now runs on error 500 :-(

**Comment by kjde** [comment]
This is an error log example:

Internal Server Error: /
Traceback (most recent call last):
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/template/base.py", line 1271, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "./core/templatetags/social.py", line 43, in social
    'homepage': context['SITE']['HOMEPAGE'],
KeyError: u'HOMEPAGE'

**Comment by mathiasertl** [comment]
I just pushed a minor update that should fix the issue.

**Comment by kjde** [comment]
It works fine after your patch :-)
