### ISSUE TITLE
Option to disable social buttons

### ISSUE THREAD

**Issue by kjde** [mathiasertl/django-xmpp-account#12]
It would be nice to have an option to disable the social share buttons. They are also not working on my installation: https://zsim.de/

**Comment by mathiasertl** [comment]
I agree, this *definetly* should be implemented. HOWEVER, I'd also like to find out why the buttons are not working for your installation. Have you done `python manage.py collectstatic` after updating?

Your javascript/css generally does seem outdated, for example the username status below the username field ("Checking username...") should be hidden with CSS - and it's not on your site.

**Comment by kjde** [comment]
# python manage.py collectstatic
No handlers could be found for logger "xmppaccount.settings"

You have requested to collect static files at the destination
location as specified in your settings:

    /home/jabberac/django-xmpp-account/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 97, in collect
    for finder in get_finders():
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 264, in get_finders
    yield get_finder(finder_path)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 277, in get_finder
    return Finder()
  File "/home/jabberac/django-xmpp-account/local/lib/python2.7/site-packages/django/contrib/staticfiles/finders.py", line 66, in __init__
    "The STATICFILES_DIRS setting should "
django.core.exceptions.ImproperlyConfigured: The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting

**Comment by mathiasertl** [comment]
This is an error in your Django configuration: `STATIC_ROOT` should be the directory by the webserver. You should not need to set the `STATICFILES_DIRS` setting unless you ship custom static files (which should not include the directory named by `STATIC_ROOT`). For more information, please google the respective django settings.

**Comment by kjde** [comment]
I configured by installation in the right way and it worked. What a wonder! :dango:

**Comment by mathiasertl** [comment]
Do you still want the feature to disable all social buttons - or are you happy with the current buttons on top?

**Comment by kjde** [comment]
It works fine for me now. However I could image that someone would like to disable Shariff.

**Comment by mathiasertl** [comment]
I will add an option in the next days :-)
